###register request
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"sajjad",
    "email":"alishadi12@gmail.com",
    "mobile":"09195687591",
    "password":"1234567",
    "confirm_password":"1234567"
}

###login request
POST  http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username":"alishahidi2",
    "password":"123456"

}


###getUser request
http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}


###edit user profile
post http://localhost:3000/user/edit-profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


{
    "first_name":"ali",
    "last_name":"shahidi",
    "skills":["prgramming","node.js","expressj.js"]
    
}



###get all req
get http://localhost:3000/user/requests
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


