###register request
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"alishahidi2",
    "email":"alishadi@gmail.com",
    "mobile":"09129421035",
    "password":"123456",
    "confirm_password":"123456"
}

###login request
POST  http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "username":"alishahidi2",
    "password":"123456"

}


###getUser request
http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}


###edit user profile
post http://localhost:3000/user/edit-profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


{
    "first_name":"ali",
    "last_name":"shahidi",
    "skills":["prgramming","node.js","expressj.js"]
    
}
